---
k3s_version: v1.31.4+k3s1
ansible_user: user
systemd_dir: /etc/systemd/system


flannel_iface: "eth0"

apiserver_endpoint: "192.168.0.52"


k3s_token: "R2WaEqo28VtB4RbbDQYDxpoFMnaMgeauhE8WbM"

extra_server_args: "--disable servicelb --disable traefik --write-kubeconfig-mode 644"
extra_agent_args: "--kubelet-arg node-status-update-frequency=5s"


kube_vip_tag_version: "v0.8.7"


metal_lb_speaker_tag_version: "0.14.9"
metal_lb_controller_tag_version: "0.14.9"
metal_lb_ip_range: "192.168.0.40-192.168.0.49"
