---
all:
  children:
    master:
      hosts:
        node1:
          ansible_host: 192.168.0.51
        node2:
          ansible_host: 192.168.0.52
        node3:
          ansible_host: 192.168.0.53
    worker:
      hosts:
        node4:
          ansible_host: 192.168.0.54
        node5:
          ansible_host: 192.168.0.55
    k3s_cluster:
      children:
        master: {}
        worker: {}
